// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tiny.proto
package upb_test;

public final class Tiny {

  public interface BabyStepsOrBuilder {

    int getFoo();

    boolean hasFoo();

    long getBar();

    boolean hasBar();

    upb_test.Tiny.Submessage getSubmsg();

    boolean hasSubmsg();

    upb_test.Tiny.BabySteps.EmbeddedMessage getEmbedded();

    boolean hasEmbedded();
  }

  public static final class BabySteps extends jupb.JupbMessageLite implements BabyStepsOrBuilder {

    private static final BabySteps DEFAULT_INSTANCE =
        new BabySteps(jupb.Arena.getDefaultInstanceArena());

    private BabySteps(jupb.Arena arena) {
      super(
          arena,
          "$<<(+33",
          4,
          upb_test.Tiny.Submessage.getDefaultInstance(),
          5,
          upb_test.Tiny.BabySteps.EmbeddedMessage.getDefaultInstance());
    }

    @java.lang.Override
    public int getFoo() {

      return jupb.Messages.getInt(pointer, 20, 12, 8, 8, 1, 1, 43);
    }

    @java.lang.Override
    public boolean hasFoo() {
      return jupb.Messages.getHasBit(pointer, 8, 8, 1, 1);
    }

    @java.lang.Override
    public long getBar() {

      return jupb.Messages.getLong(pointer, 32, 32);
    }

    @java.lang.Override
    public boolean hasBar() {
      return jupb.Messages.getHasBit(pointer, 8, 8, 2, 2);
    }

    @java.lang.Override
    public upb_test.Tiny.Submessage getSubmsg() {
      return super.getMessage(24, 40, upb_test.Tiny.Submessage.getDefaultInstance());
    }

    @java.lang.Override
    public boolean hasSubmsg() {
      return jupb.Messages.getHasBit(pointer, 8, 8, 4, 4);
    }

    @java.lang.Override
    public upb_test.Tiny.BabySteps.EmbeddedMessage getEmbedded() {
      return super.getMessage(28, 48, upb_test.Tiny.BabySteps.EmbeddedMessage.getDefaultInstance());
    }

    @java.lang.Override
    public boolean hasEmbedded() {
      return jupb.Messages.getHasBit(pointer, 8, 8, 8, 8);
    }

    public static BabySteps getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static Builder newBuilder(jupb.Arena arena) {
      return new Builder(arena, DEFAULT_INSTANCE);
    }

    public Builder toBuilder(jupb.Arena arena) {
      return new Builder(arena, this);
    }

    public static BabySteps parseFrom(jupb.Arena arena, byte[] buf)
        throws jupb.ProtocolBufferDecodingException {
      BabySteps result = new BabySteps(arena);
      jupb.Messages.decodeMessage(buf, result);
      return result;
    }

    public static final class Builder extends jupb.JupbMessageLite.Builder<BabySteps>
        implements BabyStepsOrBuilder {

      private Builder(jupb.Arena arena, BabySteps instance) {
        super(arena, instance);
      }

      @java.lang.Override
      public int getFoo() {
        return instance.getFoo();
      }

      public Builder setFoo(int value) {
        super.setInt(20, 12, 8, 8, 1, 1, value);
        return this;
      }

      @java.lang.Override
      public boolean hasFoo() {
        return instance.hasFoo();
      }

      @java.lang.Override
      public long getBar() {
        return instance.getBar();
      }

      public Builder setBar(long value) {
        super.setLong(32, 32, 8, 8, 2, 2, value);
        return this;
      }

      @java.lang.Override
      public boolean hasBar() {
        return instance.hasBar();
      }

      @java.lang.Override
      public upb_test.Tiny.Submessage getSubmsg() {
        return instance.getSubmsg();
      }

      public Builder setSubmsg(upb_test.Tiny.Submessage value) {
        super.setMessage(24, 40, 8, 8, 4, 4, value);
        return this;
      }

      @java.lang.Override
      public boolean hasSubmsg() {
        return instance.hasSubmsg();
      }

      @java.lang.Override
      public upb_test.Tiny.BabySteps.EmbeddedMessage getEmbedded() {
        return instance.getEmbedded();
      }

      public Builder setEmbedded(upb_test.Tiny.BabySteps.EmbeddedMessage value) {
        super.setMessage(28, 48, 8, 8, 8, 8, value);
        return this;
      }

      @java.lang.Override
      public boolean hasEmbedded() {
        return instance.hasEmbedded();
      }
    }

    public interface EmbeddedMessageOrBuilder {

      long getX();

      boolean hasX();
    }

    public static final class EmbeddedMessage extends jupb.JupbMessageLite
        implements EmbeddedMessageOrBuilder {

      private static final EmbeddedMessage DEFAULT_INSTANCE =
          new EmbeddedMessage(jupb.Arena.getDefaultInstanceArena());

      private EmbeddedMessage(jupb.Arena arena) {
        super(arena, "$+");
      }

      @java.lang.Override
      public long getX() {

        return jupb.Messages.getLong(pointer, 16, 16);
      }

      @java.lang.Override
      public boolean hasX() {
        return jupb.Messages.getHasBit(pointer, 8, 8, 1, 1);
      }

      public static EmbeddedMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      public static Builder newBuilder(jupb.Arena arena) {
        return new Builder(arena, DEFAULT_INSTANCE);
      }

      public Builder toBuilder(jupb.Arena arena) {
        return new Builder(arena, this);
      }

      public static EmbeddedMessage parseFrom(jupb.Arena arena, byte[] buf)
          throws jupb.ProtocolBufferDecodingException {
        EmbeddedMessage result = new EmbeddedMessage(arena);
        jupb.Messages.decodeMessage(buf, result);
        return result;
      }

      public static final class Builder extends jupb.JupbMessageLite.Builder<EmbeddedMessage>
          implements EmbeddedMessageOrBuilder {

        private Builder(jupb.Arena arena, EmbeddedMessage instance) {
          super(arena, instance);
        }

        @java.lang.Override
        public long getX() {
          return instance.getX();
        }

        public Builder setX(long value) {
          super.setLong(16, 16, 8, 8, 1, 1, value);
          return this;
        }

        @java.lang.Override
        public boolean hasX() {
          return instance.hasX();
        }
      }
    }
  }

  public interface SubmessageOrBuilder {

    int getBaz();

    boolean hasBaz();
  }

  public static final class Submessage extends jupb.JupbMessageLite implements SubmessageOrBuilder {

    private static final Submessage DEFAULT_INSTANCE =
        new Submessage(jupb.Arena.getDefaultInstanceArena());

    private Submessage(jupb.Arena arena) {
      super(arena, "$(");
    }

    @java.lang.Override
    public int getBaz() {

      return jupb.Messages.getInt(pointer, 12, 12);
    }

    @java.lang.Override
    public boolean hasBaz() {
      return jupb.Messages.getHasBit(pointer, 8, 8, 1, 1);
    }

    public static Submessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static Builder newBuilder(jupb.Arena arena) {
      return new Builder(arena, DEFAULT_INSTANCE);
    }

    public Builder toBuilder(jupb.Arena arena) {
      return new Builder(arena, this);
    }

    public static Submessage parseFrom(jupb.Arena arena, byte[] buf)
        throws jupb.ProtocolBufferDecodingException {
      Submessage result = new Submessage(arena);
      jupb.Messages.decodeMessage(buf, result);
      return result;
    }

    public static final class Builder extends jupb.JupbMessageLite.Builder<Submessage>
        implements SubmessageOrBuilder {

      private Builder(jupb.Arena arena, Submessage instance) {
        super(arena, instance);
      }

      @java.lang.Override
      public int getBaz() {
        return instance.getBaz();
      }

      public Builder setBaz(int value) {
        super.setInt(12, 12, 8, 8, 1, 1, value);
        return this;
      }

      @java.lang.Override
      public boolean hasBaz() {
        return instance.hasBaz();
      }
    }
  }
}