load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "inja",
    srcs = [
    ],
    hdrs = [
        "inja.hpp",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = ["@nlohmann_json//:json"],
)
